language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: hivemind-backend
  run: rails db:{migrate,seed}
  on:
    branch: main
notifications:
  email: false
