language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  run: rails db:{migrate}
  app:
    main: hivemind-staging-branch
    production: hivemind-backend
notifications:
  email: false
